export interface CropData {
  name: string;
  scientificName: string;
  optimalTemp: { min: number; max: number };
  optimalHumidity: { min: number; max: number };
  waterRequirement: string;
  growthPeriod: string;
  commonPests: string[];
  commonDiseases: string[];
  npkRatio: { n: number; p: number; k: number };
  harvestIndicators: string[];
  icon: string;
}

export const cropDatabase: { [key: string]: CropData } = {
  Rice: {
    name: 'Rice',
    scientificName: 'Oryza sativa',
    optimalTemp: { min: 20, max: 35 },
    optimalHumidity: { min: 70, max: 90 },
    waterRequirement: 'High',
    growthPeriod: '120-150 days',
    commonPests: ['Rice stem borer', 'Brown planthopper', 'Rice bug'],
    commonDiseases: ['Blast disease', 'Bacterial leaf blight', 'Sheath blight'],
    npkRatio: { n: 120, p: 60, k: 40 },
    harvestIndicators: ['Golden yellow color', 'Grain hardness', '80% maturity'],
    icon: '🌾',
  },
  Wheat: {
    name: 'Wheat',
    scientificName: 'Triticum aestivum',
    optimalTemp: { min: 15, max: 25 },
    optimalHumidity: { min: 50, max: 70 },
    waterRequirement: 'Moderate',
    growthPeriod: '110-130 days',
    commonPests: ['Aphids', 'Armyworm', 'Hessian fly'],
    commonDiseases: ['Rust', 'Powdery mildew', 'Fusarium head blight'],
    npkRatio: { n: 100, p: 50, k: 30 },
    harvestIndicators: ['Hard grain', 'Straw turns yellow', 'Moisture 12-14%'],
    icon: '🌾',
  },
  Corn: {
    name: 'Corn',
    scientificName: 'Zea mays',
    optimalTemp: { min: 18, max: 32 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'High',
    growthPeriod: '90-120 days',
    commonPests: ['Corn borer', 'Fall armyworm', 'Cutworm'],
    commonDiseases: ['Corn smut', 'Gray leaf spot', 'Northern corn leaf blight'],
    npkRatio: { n: 150, p: 75, k: 60 },
    harvestIndicators: ['Kernels dent', 'Husk turns brown', 'Black layer forms'],
    icon: '🌽',
  },
  Tomato: {
    name: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    optimalTemp: { min: 18, max: 27 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Moderate to High',
    growthPeriod: '60-85 days',
    commonPests: ['Whitefly', 'Aphids', 'Tomato hornworm'],
    commonDiseases: ['Early blight', 'Late blight', 'Fusarium wilt'],
    npkRatio: { n: 100, p: 80, k: 120 },
    harvestIndicators: ['Full color development', 'Firm texture', 'Glossy skin'],
    icon: '🍅',
  },
  Potato: {
    name: 'Potato',
    scientificName: 'Solanum tuberosum',
    optimalTemp: { min: 15, max: 20 },
    optimalHumidity: { min: 70, max: 85 },
    waterRequirement: 'Moderate',
    growthPeriod: '90-120 days',
    commonPests: ['Colorado potato beetle', 'Aphids', 'Wireworm'],
    commonDiseases: ['Late blight', 'Early blight', 'Potato scab'],
    npkRatio: { n: 80, p: 100, k: 120 },
    harvestIndicators: ['Foliage yellowing', 'Skin sets firmly', 'Tuber maturity'],
    icon: '🥔',
  },
  Cotton: {
    name: 'Cotton',
    scientificName: 'Gossypium',
    optimalTemp: { min: 21, max: 30 },
    optimalHumidity: { min: 50, max: 70 },
    waterRequirement: 'Moderate',
    growthPeriod: '150-180 days',
    commonPests: ['Bollworm', 'Aphids', 'Whitefly'],
    commonDiseases: ['Fusarium wilt', 'Verticillium wilt', 'Bacterial blight'],
    npkRatio: { n: 120, p: 60, k: 60 },
    harvestIndicators: ['Bolls open', 'Fiber white', '60% bolls open'],
    icon: '🌱',
  },
  Soybean: {
    name: 'Soybean',
    scientificName: 'Glycine max',
    optimalTemp: { min: 20, max: 30 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Moderate',
    growthPeriod: '90-150 days',
    commonPests: ['Soybean aphid', 'Bean leaf beetle', 'Stink bugs'],
    commonDiseases: ['Soybean rust', 'Frogeye leaf spot', 'White mold'],
    npkRatio: { n: 40, p: 80, k: 60 },
    harvestIndicators: ['Leaves drop', 'Pods brown', 'Seeds rattle'],
    icon: '🫘',
  },
  Sugarcane: {
    name: 'Sugarcane',
    scientificName: 'Saccharum officinarum',
    optimalTemp: { min: 20, max: 35 },
    optimalHumidity: { min: 70, max: 90 },
    waterRequirement: 'High',
    growthPeriod: '12-18 months',
    commonPests: ['Sugarcane borer', 'Aphids', 'Whitefly'],
    commonDiseases: ['Red rot', 'Smut', 'Rust'],
    npkRatio: { n: 150, p: 60, k: 80 },
    harvestIndicators: ['Sweet taste', 'Yellow leaves', 'Hard stalks'],
    icon: '🎋',
  },
  Onion: {
    name: 'Onion',
    scientificName: 'Allium cepa',
    optimalTemp: { min: 13, max: 24 },
    optimalHumidity: { min: 65, max: 75 },
    waterRequirement: 'Moderate',
    growthPeriod: '90-120 days',
    commonPests: ['Onion thrips', 'Onion maggot', 'Cutworm'],
    commonDiseases: ['Purple blotch', 'Downy mildew', 'Onion smut'],
    npkRatio: { n: 80, p: 40, k: 80 },
    harvestIndicators: ['Tops fall over', 'Neck softens', 'Bulb fully formed'],
    icon: '🧅',
  },
  Carrot: {
    name: 'Carrot',
    scientificName: 'Daucus carota',
    optimalTemp: { min: 16, max: 21 },
    optimalHumidity: { min: 65, max: 75 },
    waterRequirement: 'Moderate',
    growthPeriod: '70-80 days',
    commonPests: ['Carrot fly', 'Aphids', 'Wireworm'],
    commonDiseases: ['Leaf blight', 'Black rot', 'Cavity spot'],
    npkRatio: { n: 60, p: 80, k: 100 },
    harvestIndicators: ['Orange color', 'Proper size', 'Firm texture'],
    icon: '🥕',
  },
  Coffee: {
    name: 'Coffee',
    scientificName: 'Coffea arabica',
    optimalTemp: { min: 18, max: 24 },
    optimalHumidity: { min: 60, max: 70 },
    waterRequirement: 'High',
    growthPeriod: '3-5 years to first harvest',
    commonPests: ['Coffee berry borer', 'Leaf rust', 'Scale insects'],
    commonDiseases: ['Coffee leaf rust', 'Coffee berry disease', 'Root rot'],
    npkRatio: { n: 100, p: 50, k: 80 },
    harvestIndicators: ['Red cherry color', 'Firm berries', 'Sweet aroma'],
    icon: '☕',
  },
  Avocado: {
    name: 'Avocado',
    scientificName: 'Persea americana',
    optimalTemp: { min: 20, max: 30 },
    optimalHumidity: { min: 50, max: 70 },
    waterRequirement: 'Moderate to High',
    growthPeriod: '3-6 years to first harvest',
    commonPests: ['Avocado thrips', 'Scale insects', 'Mites'],
    commonDiseases: ['Root rot', 'Anthracnose', 'Scab'],
    npkRatio: { n: 80, p: 40, k: 120 },
    harvestIndicators: ['Fruit yields to pressure', 'Skin darkens', 'Stem end soft'],
    icon: '🥑',
  },
  Banana: {
    name: 'Banana',
    scientificName: 'Musa acuminata',
    optimalTemp: { min: 26, max: 30 },
    optimalHumidity: { min: 75, max: 85 },
    waterRequirement: 'High',
    growthPeriod: '9-12 months',
    commonPests: ['Banana weevil', 'Nematodes', 'Aphids'],
    commonDiseases: ['Panama disease', 'Black sigatoka', 'Bunchy top'],
    npkRatio: { n: 200, p: 50, k: 300 },
    harvestIndicators: ['Fingers plump', 'Light green color', 'Ridges less prominent'],
    icon: '🍌',
  },
  Mango: {
    name: 'Mango',
    scientificName: 'Mangifera indica',
    optimalTemp: { min: 24, max: 35 },
    optimalHumidity: { min: 50, max: 75 },
    waterRequirement: 'Moderate',
    growthPeriod: '3-5 years to first harvest',
    commonPests: ['Mango hoppers', 'Scale insects', 'Fruit flies'],
    commonDiseases: ['Anthracnose', 'Powdery mildew', 'Bacterial canker'],
    npkRatio: { n: 100, p: 50, k: 100 },
    harvestIndicators: ['Color change', 'Sweet aroma', 'Slight softness'],
    icon: '🥭',
  },
  Coconut: {
    name: 'Coconut',
    scientificName: 'Cocos nucifera',
    optimalTemp: { min: 27, max: 35 },
    optimalHumidity: { min: 70, max: 85 },
    waterRequirement: 'High',
    growthPeriod: '5-6 years to first harvest',
    commonPests: ['Rhinoceros beetle', 'Red palm weevil', 'Scale insects'],
    commonDiseases: ['Lethal yellowing', 'Bud rot', 'Stem bleeding'],
    npkRatio: { n: 120, p: 40, k: 140 },
    harvestIndicators: ['Brown husk', 'Water sound when shaken', 'Heavy weight'],
    icon: '🥥',
  },
  Cacao: {
    name: 'Cacao',
    scientificName: 'Theobroma cacao',
    optimalTemp: { min: 21, max: 32 },
    optimalHumidity: { min: 75, max: 85 },
    waterRequirement: 'High',
    growthPeriod: '3-5 years to first harvest',
    commonPests: ['Cocoa pod borer', 'Mirids', 'Thrips'],
    commonDiseases: ['Black pod disease', 'Witches broom', 'Frosty pod rot'],
    npkRatio: { n: 100, p: 30, k: 150 },
    harvestIndicators: ['Pod color change', 'Hollow sound when tapped', 'Ripe aroma'],
    icon: '🍫',
  },
  Papaya: {
    name: 'Papaya',
    scientificName: 'Carica papaya',
    optimalTemp: { min: 21, max: 33 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Moderate to High',
    growthPeriod: '6-12 months',
    commonPests: ['Papaya fruit fly', 'Aphids', 'Spider mites'],
    commonDiseases: ['Papaya ringspot virus', 'Anthracnose', 'Black spot'],
    npkRatio: { n: 120, p: 60, k: 120 },
    harvestIndicators: ['Yellow-orange color', 'Slight softness', 'Sweet aroma'],
    icon: '🫐',
  },
  Pineapple: {
    name: 'Pineapple',
    scientificName: 'Ananas comosus',
    optimalTemp: { min: 23, max: 32 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Low to Moderate',
    growthPeriod: '18-24 months',
    commonPests: ['Mealybugs', 'Scale insects', 'Nematodes'],
    commonDiseases: ['Heart rot', 'Fruit core rot', 'Pink disease'],
    npkRatio: { n: 80, p: 40, k: 120 },
    harvestIndicators: ['Golden color', 'Sweet aroma', 'Hollow sound'],
    icon: '🍍',
  },
  Lettuce: {
    name: 'Lettuce',
    scientificName: 'Lactuca sativa',
    optimalTemp: { min: 15, max: 20 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Moderate',
    growthPeriod: '45-65 days',
    commonPests: ['Aphids', 'Cutworms', 'Leaf miners'],
    commonDiseases: ['Downy mildew', 'Lettuce drop', 'Tipburn'],
    npkRatio: { n: 80, p: 40, k: 60 },
    harvestIndicators: ['Full head formation', 'Crisp leaves', 'Before bolting'],
    icon: '🥬',
  },
  Spinach: {
    name: 'Spinach',
    scientificName: 'Spinacia oleracea',
    optimalTemp: { min: 10, max: 18 },
    optimalHumidity: { min: 65, max: 75 },
    waterRequirement: 'Moderate',
    growthPeriod: '40-50 days',
    commonPests: ['Leaf miners', 'Aphids', 'Flea beetles'],
    commonDiseases: ['Downy mildew', 'White rust', 'Fusarium wilt'],
    npkRatio: { n: 100, p: 50, k: 80 },
    harvestIndicators: ['Leaves 6+ inches', 'Dark green color', 'Before flowering'],
    icon: '🥬',
  },
  Pepper: {
    name: 'Pepper',
    scientificName: 'Capsicum annuum',
    optimalTemp: { min: 21, max: 29 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Moderate',
    growthPeriod: '70-90 days',
    commonPests: ['Aphids', 'Thrips', 'Pepper weevil'],
    commonDiseases: ['Bacterial spot', 'Phytophthora blight', 'Virus diseases'],
    npkRatio: { n: 100, p: 80, k: 120 },
    harvestIndicators: ['Full size', 'Color change', 'Firm texture'],
    icon: '🌶️',
  },
  Cucumber: {
    name: 'Cucumber',
    scientificName: 'Cucumis sativus',
    optimalTemp: { min: 18, max: 24 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'High',
    growthPeriod: '50-70 days',
    commonPests: ['Cucumber beetles', 'Aphids', 'Spider mites'],
    commonDiseases: ['Downy mildew', 'Powdery mildew', 'Bacterial wilt'],
    npkRatio: { n: 80, p: 60, k: 100 },
    harvestIndicators: ['Uniform green color', 'Firm texture', 'Before yellowing'],
    icon: '🥒',
  },
  Eggplant: {
    name: 'Eggplant',
    scientificName: 'Solanum melongena',
    optimalTemp: { min: 21, max: 30 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Moderate to High',
    growthPeriod: '80-100 days',
    commonPests: ['Flea beetles', 'Colorado potato beetle', 'Aphids'],
    commonDiseases: ['Verticillium wilt', 'Bacterial wilt', 'Phomopsis blight'],
    npkRatio: { n: 100, p: 80, k: 120 },
    harvestIndicators: ['Glossy skin', 'Full size', 'Before seeds harden'],
    icon: '🍆',
  },
  Okra: {
    name: 'Okra',
    scientificName: 'Abelmoschus esculentus',
    optimalTemp: { min: 24, max: 35 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Moderate',
    growthPeriod: '50-65 days',
    commonPests: ['Aphids', 'Flea beetles', 'Stink bugs'],
    commonDiseases: ['Fusarium wilt', 'Powdery mildew', 'Root knot nematode'],
    npkRatio: { n: 80, p: 60, k: 80 },
    harvestIndicators: ['Tender pods', '3-4 inches long', 'Before fiber develops'],
    icon: '🌶️',
  },
  Cabbage: {
    name: 'Cabbage',
    scientificName: 'Brassica oleracea',
    optimalTemp: { min: 15, max: 20 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Moderate to High',
    growthPeriod: '70-100 days',
    commonPests: ['Cabbage worms', 'Aphids', 'Flea beetles'],
    commonDiseases: ['Clubroot', 'Black rot', 'Downy mildew'],
    npkRatio: { n: 120, p: 60, k: 100 },
    harvestIndicators: ['Firm head', 'Good size', 'Before splitting'],
    icon: '🥬',
  },
  Cauliflower: {
    name: 'Cauliflower',
    scientificName: 'Brassica oleracea var. botrytis',
    optimalTemp: { min: 15, max: 18 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'High',
    growthPeriod: '75-85 days',
    commonPests: ['Cabbage worms', 'Aphids', 'Diamondback moth'],
    commonDiseases: ['Clubroot', 'Black rot', 'Downy mildew'],
    npkRatio: { n: 150, p: 80, k: 120 },
    harvestIndicators: ['White compact head', 'Before florets separate', 'Firm texture'],
    icon: '🥦',
  },
  Broccoli: {
    name: 'Broccoli',
    scientificName: 'Brassica oleracea var. italica',
    optimalTemp: { min: 15, max: 18 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'High',
    growthPeriod: '70-80 days',
    commonPests: ['Cabbage worms', 'Aphids', 'Flea beetles'],
    commonDiseases: ['Clubroot', 'Black rot', 'Downy mildew'],
    npkRatio: { n: 150, p: 80, k: 120 },
    harvestIndicators: ['Tight green head', 'Before flowers open', 'Side shoots develop'],
    icon: '🥦',
  },
  Beans: {
    name: 'Beans',
    scientificName: 'Phaseolus vulgaris',
    optimalTemp: { min: 18, max: 24 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Moderate',
    growthPeriod: '50-60 days (bush), 60-70 days (pole)',
    commonPests: ['Bean beetles', 'Aphids', 'Spider mites'],
    commonDiseases: ['Bacterial blight', 'Rust', 'Mosaic virus'],
    npkRatio: { n: 40, p: 80, k: 60 },
    harvestIndicators: ['Pods snap easily', 'Seeds not bulging', 'Tender texture'],
    icon: '🫘',
  },
  Peas: {
    name: 'Peas',
    scientificName: 'Pisum sativum',
    optimalTemp: { min: 13, max: 18 },
    optimalHumidity: { min: 60, max: 80 },
    waterRequirement: 'Moderate',
    growthPeriod: '60-70 days',
    commonPests: ['Pea aphids', 'Pea weevil', 'Thrips'],
    commonDiseases: ['Powdery mildew', 'Root rot', 'Pea enation mosaic'],
    npkRatio: { n: 40, p: 80, k: 60 },
    harvestIndicators: ['Plump pods', 'Bright green color', 'Sweet taste'],
    icon: '🟢',
  },
};
